services:
  # Backend API Service
  - type: web
    name: supportcraft-pro-support-widget-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://supportcraft-pro.onrender.com
      - key: WIDGET_ORIGIN
        value: "*"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Admin Frontend Web Service with SPA Support
  - type: web
    name: supportcraft-pro
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd admin-frontend && npm install && npm run build
    startCommand: cd admin-frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Widget Static Site
  - type: web
    name: supportcraft-pro-widget
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd widget && npm install && npm run build
    staticPublishPath: ./widget/dist

